In [2]:
import pandas as pd 
driver_df_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024 Datasets/raw_driver_2024.csv")
driver_df_2024.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,RoundNumber,GP,Session,Date
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1,1,NaN,NaN,NaN,0 days 00:00:41.266000,...,12,1.0,False,NaN,False,False,1,Bahrain Grand Prix,R,02-03-2024
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2,1,NaN,NaN,0 days 00:00:30.916000,0 days 00:00:41.661000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3,1,NaN,NaN,0 days 00:00:30.999000,0 days 00:00:41.966000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4,1,NaN,NaN,0 days 00:00:30.931000,0 days 00:00:41.892000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5,1,NaN,NaN,0 days 00:00:31.255000,0 days 00:00:42.056000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024

In [4]:
driver_df_2024.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate', 'RoundNumber', 'GP', 'Session',
       'Date'],
      dtype='object')

In [5]:
driver_df_2024.dtypes

Time                   object
Driver                 object
DriverNumber            int64
LapTime                object
LapNumber             float64
Stint                 float64
PitOutTime             object
PitInTime              object
Sector1Time            object
Sector2Time            object
Sector3Time            object
Sector1SessionTime     object
Sector2SessionTime     object
Sector3SessionTime     object
SpeedI1               float64
SpeedI2               float64
SpeedFL               float64
SpeedST               float64
IsPersonalBest         object
Compound               object
TyreLife              float64
FreshTyre                bool
Team                   object
LapStartTime           object
LapStartDate           object
TrackStatus             int64
Position              float64
Deleted                  bool
DeletedReason          object
FastF1Generated          bool
IsAccurate               bool
RoundNumber             int64
GP                     object
Session                object
Date                   object
dtype: object

In [3]:
weather_df_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024 Datasets/weather_2024.csv")
weather_df_2024.head(5)

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed,RoundNumber,EventName,Session,Date
0,0 days 00:00:44.852000,19.7,38.0,1016.2,False,35.8,84,3.7,1,Bahrain Grand Prix,FP1,2024-03-02
1,0 days 00:01:44.867000,19.8,38.0,1016.0,False,35.8,73,3.4,1,Bahrain Grand Prix,FP1,2024-03-02
2,0 days 00:02:44.873000,19.7,38.0,1016.2,False,35.9,72,4.1,1,Bahrain Grand Prix,FP1,2024-03-02
3,0 days 00:03:44.889000,19.7,38.0,1016.2,False,35.9,83,3.7,1,Bahrain Grand Prix,FP1,2024-03-02
4,0 days 00:04:44.894000,19.7,38.0,1016.1,False,35.9,89,4.0,1,Bahrain Grand Prix,FP1,2024-03-02

In [5]:
clean_weather_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024 Datasets/cleaned_weather_2024.csv")
clean_weather_2024.head(5)

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed,RoundNumber,EventName,Session,Date
0,0 days 00:00:44.852000,19.7,38.0,1016.2,False,35.8,84.0,3.7,1,Bahrain Grand Prix,FP1,2024-03-02
1,0 days 00:01:44.867000,19.8,38.0,1016.0,False,35.8,73.0,3.4,1,Bahrain Grand Prix,FP1,2024-03-02
2,0 days 00:02:44.873000,19.7,38.0,1016.2,False,35.9,72.0,4.1,1,Bahrain Grand Prix,FP1,2024-03-02
3,0 days 00:03:44.889000,19.7,38.0,1016.2,False,35.9,83.0,3.7,1,Bahrain Grand Prix,FP1,2024-03-02
4,0 days 00:04:44.894000,19.7,38.0,1016.1,False,35.9,89.0,4.0,1,Bahrain Grand Prix,FP1,2024-03-02

In [9]:
clean_weather_2024.dtypes

Time              object
AirTemp          float64
Humidity         float64
Pressure         float64
Rainfall            bool
TrackTemp        float64
WindDirection    float64
WindSpeed        float64
RoundNumber        int64
EventName         object
Session           object
Date              object
dtype: object

In [10]:
driver_df_2024 = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024 Datasets/cleaned_driver_2024.csv")
driver_df_2024.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,RoundNumber,GP,Session,Date
0,0 days 01:01:37.489000,VER,1,97.284,1,1,NaN,NaN,NaN,41.266,...,12,1.0,False,NaN,False,False,1,Bahrain Grand Prix,R,02-03-2024
1,0 days 01:03:13.785000,VER,1,96.296,2,1,NaN,NaN,30.916,41.661,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
2,0 days 01:04:50.538000,VER,1,96.753,3,1,NaN,NaN,30.999,41.966,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
3,0 days 01:06:27.185000,VER,1,96.647,4,1,NaN,NaN,30.931,41.892,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
4,0 days 01:08:04.358000,VER,1,97.173,5,1,NaN,NaN,31.255,42.056,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024

In [14]:
driver_df_2024_raw = pd.read_csv("C:/Users/VANSH/Formula1/datasets/2024 Datasets/raw_driver_2024.csv")
driver_df_2024_raw.head(5)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,RoundNumber,GP,Session,Date
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1,1,NaN,NaN,NaN,0 days 00:00:41.266000,...,12,1.0,False,NaN,False,False,1,Bahrain Grand Prix,R,02-03-2024
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2,1,NaN,NaN,0 days 00:00:30.916000,0 days 00:00:41.661000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3,1,NaN,NaN,0 days 00:00:30.999000,0 days 00:00:41.966000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4,1,NaN,NaN,0 days 00:00:30.931000,0 days 00:00:41.892000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5,1,NaN,NaN,0 days 00:00:31.255000,0 days 00:00:42.056000,...,1,1.0,False,NaN,False,True,1,Bahrain Grand Prix,R,02-03-2024

In [15]:
driver_df_2024_raw['Session'].value_counts()

Session
R    26604
Name: count, dtype: int64